/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Development;

import Development.MCBank;
import Development.MCBank;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.security.util.Password;

/**
 *
 * @author micha
 */
public class LoginFormV2 extends javax.swing.JFrame {

    private MCBank bank;
    /**
     * Creates new form LoginFormV2
     * @param bank
     */
    public LoginFormV2(MCBank bank) {
        initComponents();
        this.bank = bank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pwIcon = new javax.swing.JLabel();
        unIcon = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JLabel();
        promptLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setResizable(false);

        iconPanel.setBackground(java.awt.Color.darkGray);
        iconPanel.setPreferredSize(new java.awt.Dimension(325, 350));
        iconPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.darkGray);
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Development/bankIcon.png"))); // NOI18N
        iconPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 100));

        jLabel2.setBackground(java.awt.Color.darkGray);
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MC BANK");
        iconPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 30));

        controlPanel.setBackground(new java.awt.Color(51, 51, 51));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setBackground(new java.awt.Color(51, 51, 51));
        userField.setForeground(new java.awt.Color(204, 204, 204));
        userField.setText("Username");
        userField.setBorder(null);
        userField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userFieldMouseClicked(evt);
            }
        });
        controlPanel.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 200, 30));

        passField.setBackground(new java.awt.Color(51, 51, 51));
        passField.setForeground(new java.awt.Color(204, 204, 204));
        passField.setText("Password");
        passField.setBorder(null);
        passField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passFieldMouseClicked(evt);
            }
        });
        controlPanel.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 200, 30));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        controlPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 200, 10));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        controlPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 200, 10));

        pwIcon.setBackground(new java.awt.Color(204, 204, 204));
        pwIcon.setForeground(new java.awt.Color(204, 204, 204));
        pwIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Development/lockIcon.png"))); // NOI18N
        controlPanel.add(pwIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        unIcon.setBackground(new java.awt.Color(204, 204, 204));
        unIcon.setForeground(new java.awt.Color(204, 204, 204));
        unIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Development/userIcon.png"))); // NOI18N
        controlPanel.add(unIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 30));

        exitLabel.setBackground(new java.awt.Color(51, 51, 51));
        exitLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(204, 204, 204));
        exitLabel.setText("X");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        controlPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 20, 30));

        registerPanel.setBackground(new java.awt.Color(51, 51, 51));
        registerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        registerButton.setBackground(new java.awt.Color(51, 51, 51));
        registerButton.setForeground(new java.awt.Color(204, 204, 204));
        registerButton.setText("      SIGN UP");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        controlPanel.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 80, 20));

        loginPanel.setBackground(new java.awt.Color(51, 51, 51));
        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        loginButton.setBackground(new java.awt.Color(51, 51, 51));
        loginButton.setForeground(new java.awt.Color(204, 204, 204));
        loginButton.setText("       LOGIN");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        controlPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, 20));

        promptLabel.setForeground(new java.awt.Color(204, 204, 204));
        promptLabel.setText(" ");
        controlPanel.add(promptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.out.println("Closing Application...");
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("LOGIN CLICKED");
        

        if(passField.getText().equals("test") && userField.getText().equalsIgnoreCase("test")) {
            this.promptLabel.setForeground(Color.GREEN);
            this.promptLabel.setText("Login Successful!");
        }
        else {
            this.promptLabel.setForeground(Color.RED);
            this.promptLabel.setText("Incorrect User/Password!");
        }
        
    }//GEN-LAST:event_loginButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        System.out.println("SIGN UP CLICKED");
    }//GEN-LAST:event_registerButtonMouseClicked

    private void userFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userFieldMouseClicked
        // TODO add your handling code here:
        this.userField.setText("");
    }//GEN-LAST:event_userFieldMouseClicked

    private void passFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passFieldMouseClicked
        // TODO add your handling code here:
        this.passField.setText("");
    }//GEN-LAST:event_passFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LoginFormV2(bank).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JLabel pwIcon;
    private javax.swing.JLabel registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel unIcon;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
