/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Development;

import java.awt.Color;

/**
 *
 * @author micha
 */
public class RegistrationForm extends javax.swing.JFrame {

    private static MCBank bank;
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm(MCBank bank) {
        initComponents();
        this.bank = bank;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        windowLabel = new javax.swing.JLabel();
        pwConfLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        userRegLabel = new javax.swing.JLabel();
        pwRegLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        userRegField = new javax.swing.JTextField();
        pwConfField = new javax.swing.JPasswordField();
        pwRegField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        createAccountButton = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        regPromptLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Registration"); // NOI18N
        setSize(new java.awt.Dimension(580, 365));

        regPanel.setBackground(new java.awt.Color(51, 51, 51));
        regPanel.setPreferredSize(new java.awt.Dimension(530, 368));
        regPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLabel.setBackground(new java.awt.Color(51, 51, 51));
        iconLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        iconLabel.setForeground(new java.awt.Color(204, 204, 204));
        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Development/Icons/bankIcon.png"))); // NOI18N
        regPanel.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 90, -1));

        windowLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        windowLabel.setForeground(new java.awt.Color(204, 204, 204));
        windowLabel.setText("  REGISTRATION");
        regPanel.add(windowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, 50));

        pwConfLabel.setBackground(new java.awt.Color(204, 204, 204));
        pwConfLabel.setForeground(new java.awt.Color(204, 204, 204));
        pwConfLabel.setText("Confirm Password:");
        regPanel.add(pwConfLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        firstNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        firstNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        firstNameLabel.setText("Firstname:");
        regPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lastNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        lastNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        lastNameLabel.setText("Lastname:");
        regPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        userRegLabel.setBackground(new java.awt.Color(204, 204, 204));
        userRegLabel.setForeground(new java.awt.Color(204, 204, 204));
        userRegLabel.setText("Username:");
        regPanel.add(userRegLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        pwRegLabel.setBackground(new java.awt.Color(204, 204, 204));
        pwRegLabel.setForeground(new java.awt.Color(204, 204, 204));
        pwRegLabel.setText("Password:");
        regPanel.add(pwRegLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        firstNameField.setBackground(new java.awt.Color(51, 51, 51));
        firstNameField.setForeground(new java.awt.Color(204, 204, 204));
        firstNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        regPanel.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, -1));

        lastNameField.setBackground(new java.awt.Color(51, 51, 51));
        lastNameField.setForeground(new java.awt.Color(204, 204, 204));
        lastNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        regPanel.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, -1));

        userRegField.setBackground(new java.awt.Color(51, 51, 51));
        userRegField.setForeground(new java.awt.Color(204, 204, 204));
        userRegField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        regPanel.add(userRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, -1));

        pwConfField.setBackground(new java.awt.Color(51, 51, 51));
        pwConfField.setForeground(new java.awt.Color(204, 204, 204));
        pwConfField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        regPanel.add(pwConfField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 220, -1));

        pwRegField.setBackground(new java.awt.Color(51, 51, 51));
        pwRegField.setForeground(new java.awt.Color(204, 204, 204));
        pwRegField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        regPanel.add(pwRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 220, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        createAccountButton.setBackground(new java.awt.Color(51, 51, 51));
        createAccountButton.setForeground(new java.awt.Color(204, 204, 204));
        createAccountButton.setText("      CREATE ACCOUNT");
        createAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        regPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 140, 20));

        bankLabel.setBackground(java.awt.Color.darkGray);
        bankLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bankLabel.setForeground(new java.awt.Color(255, 255, 255));
        bankLabel.setText("MC BANK");
        regPanel.add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 90, 30));

        regPromptLabel.setBackground(new java.awt.Color(51, 51, 51));
        regPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regPromptLabel.setForeground(new java.awt.Color(204, 204, 204));
        regPromptLabel.setText(" ");
        regPanel.add(regPromptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountButtonMouseClicked
        // TODO add your handling code here:
        if(!pwRegField.getText().equals(pwConfField.getText())) {
            this.regPromptLabel.setForeground(Color.RED);
            this.regPromptLabel.setText("Password Mismatch!");            
        }
        else if(bank.getAccDetailMap().containsKey(userRegField.getText())) {
            this.regPromptLabel.setForeground(Color.RED);
            this.regPromptLabel.setText("Username Taken!");               
        }
        else {
            this.regPromptLabel.setForeground(Color.GREEN);
            this.regPromptLabel.setText("Account Created!"); 
            bank.createAccount(userRegField.getText(), pwRegField.getText(), firstNameField.getText(), lastNameField.getText());
        }
    }//GEN-LAST:event_createAccountButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel createAccountButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPasswordField pwConfField;
    private javax.swing.JLabel pwConfLabel;
    private javax.swing.JPasswordField pwRegField;
    private javax.swing.JLabel pwRegLabel;
    private javax.swing.JPanel regPanel;
    private javax.swing.JLabel regPromptLabel;
    private javax.swing.JTextField userRegField;
    private javax.swing.JLabel userRegLabel;
    private javax.swing.JLabel windowLabel;
    // End of variables declaration//GEN-END:variables
}
